# Generated by Django 3.2.2 on 2021-05-09 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Custumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=None, max_length=255)),
                ('email', models.EmailField(blank=True, default=None, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255)),
                ('price', models.IntegerField()),
                ('state', models.IntegerField(choices=[(0, 'vacant'), (1, 'occupied'), (2, 'for cleaning')])),
            ],
        ),
    ]
