# Generated by Django 3.2.2 on 2021-05-09 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hms_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='custumer',
            name='number',
            field=phonenumber_field.modelfields.PhoneNumberField(default=None, max_length=128, region=None),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('target_date', models.DateField(default=None)),
                ('claimed', models.BooleanField(default=False)),
                ('days', models.IntegerField(default=8)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('custumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hms_site.custumer')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hms_site.room')),
            ],
        ),
    ]
