# Generated by Django 3.2.2 on 2021-05-09 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms_site', '0002_auto_20210509_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='days',
            field=models.IntegerField(default=1),
        ),
    ]
