# Generated by Django 3.2.2 on 2021-05-10 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms_site', '0003_alter_reservation_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='customer_name',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
