# Generated by Django 3.2.2 on 2021-05-10 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hms_site', '0006_alter_reservation_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='custumer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hms_site.custumer'),
        ),
    ]
