# Generated by Django 3.2.2 on 2021-05-10 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms_site', '0008_auto_20210510_0916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='days',
        ),
        migrations.AddField(
            model_name='reservation',
            name='check_out_date',
            field=models.DateField(default=None),
        ),
    ]
