# Generated by Django 3.2.2 on 2021-05-10 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms_site', '0009_auto_20210511_0642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='state',
        ),
        migrations.AddField(
            model_name='room',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
